CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "balance" decimal(10,2) DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Games" (
  "game_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "release_date" date,
  "cover_url" varchar,
  "genre" varchar
);

CREATE TABLE "Stores" (
  "store_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "type" varchar,
  "api_url" varchar
);

CREATE TABLE "Sellers" (
  "seller_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" int,
  "name" varchar,
  "rating" decimal(3,2),
  "sales_count" int DEFAULT 0
);

CREATE TABLE "Offers" (
  "offer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int,
  "store_id" int,
  "seller_id" int,
  "price" decimal(10,2) NOT NULL,
  "discount_percent" int DEFAULT 0,
  "cashback_percent" int DEFAULT 0,
  "region" varchar,
  "updated_at" timestamp
);

CREATE TABLE "PriceHistory" (
  "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int,
  "store_id" int,
  "price" decimal(10,2) NOT NULL,
  "recorded_at" timestamp DEFAULT (now())
);

CREATE TABLE "Wishlists" (
  "wishlist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "game_id" int,
  "target_price" decimal(10,2),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Notifications" (
  "notification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "game_id" int,
  "message" text,
  "is_read" boolean DEFAULT false,
  "sent_at" timestamp DEFAULT (now())
);

CREATE TABLE "Transactions" (
  "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "offer_id" int,
  "amount" decimal(10,2) NOT NULL,
  "cashback_earned" decimal(10,2) DEFAULT 0,
  "status" varchar,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "Stores"."type" IS 'официальный магазин или маркетплейс';

COMMENT ON COLUMN "Offers"."region" IS 'Регион активации ключа';

COMMENT ON COLUMN "Wishlists"."target_price" IS 'Желаемая цена пользователя';

COMMENT ON COLUMN "Transactions"."status" IS 'pending, completed, failed';

ALTER TABLE "Sellers" ADD FOREIGN KEY ("store_id") REFERENCES "Stores" ("store_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Offers" ADD FOREIGN KEY ("game_id") REFERENCES "Games" ("game_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Offers" ADD FOREIGN KEY ("store_id") REFERENCES "Stores" ("store_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Offers" ADD FOREIGN KEY ("seller_id") REFERENCES "Sellers" ("seller_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PriceHistory" ADD FOREIGN KEY ("game_id") REFERENCES "Games" ("game_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PriceHistory" ADD FOREIGN KEY ("store_id") REFERENCES "Stores" ("store_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Wishlists" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Wishlists" ADD FOREIGN KEY ("game_id") REFERENCES "Games" ("game_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Notifications" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Notifications" ADD FOREIGN KEY ("game_id") REFERENCES "Games" ("game_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Transactions" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Transactions" ADD FOREIGN KEY ("offer_id") REFERENCES "Offers" ("offer_id") DEFERRABLE INITIALLY IMMEDIATE;
